name: Continuous Deployment

on:
  push:
    branches: [main]

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-24.04

    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Set up node
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Install dependencies
        run: npn ci

      - name: Build
        run: npm run build
