name: Continuous Integration

on:
  pull_request:
    branches: [main]

jobs:
  tests:
    name: Tests
    runs-on: ubuntu-24.04

    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Set up node
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Print node version
        run: node --version

      - name: Install dependencies
        run: npm ci

      - name: Unit test
        run: npm run test -- --coverage

  style:
    name: Style
    runs-on: ubuntu-24.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up node
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Install dependencies
        run: npm ci

      - name: Check format
        run: npm run format:check

      - name: Check linting
        run: npm run lint -- --max-warnings=0
